### ISSUE TITLE
Using `request_userinfo` with Google OpenID results in `Jose(UnsupportedOperation)`.

### ISSUE THREAD

**Issue by xfbs** [kilork/openid#42] opened 2023-04-08 19:43 UTC
Using `request_userinfo` with Google OpenID results in `Jose(UnsupportedOperation).` I have to manually make a request to https://www.googleapis.com/oauth2/v3/userinfo to get info. Is this a bug or am I using the library wrong? I can provide some code if needed.

**Comment by kilork** [comment] 2023-04-09 05:41
Hi, I recently was changing this place. I would recommend to test with previous version, to check if this is the regression. If it is not solving your issue, maybe you may provide your code, because I test my implementation after updates with google variant first.

You may find example here: https://github.com/kilork/openid-examples/blob/main/examples/warp.rs

**Comment by kilork** [comment] 2023-05-18 12:02
No feedback, closing issue.

**Closed by kilork** 2023-05-18 12:02 UTC
